-- 在 Supabase SQL Editor 中执行本文件。
-- 账号密码由 Supabase Auth 管理；public schema 不保存密码或密码哈希。

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null default '用户',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.login_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null default 'sign_in' check (event_type in ('sign_in', 'sign_up')),
  user_agent text,
  logged_in_at timestamptz not null default now()
);

create index if not exists login_events_user_time_idx
  on public.login_events (user_id, logged_in_at desc);

create table if not exists public.user_data (
  user_id uuid not null references auth.users(id) on delete cascade,
  data_key text not null,
  data_value text not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, data_key)
);

alter table public.profiles enable row level security;
alter table public.login_events enable row level security;
alter table public.user_data enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  using ((select auth.uid()) = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

drop policy if exists "Users can read own login events" on public.login_events;
create policy "Users can read own login events"
  on public.login_events for select
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own login events" on public.login_events;
create policy "Users can insert own login events"
  on public.login_events for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read own app data" on public.user_data;
create policy "Users can read own app data"
  on public.user_data for select
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own app data" on public.user_data;
create policy "Users can insert own app data"
  on public.user_data for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own app data" on public.user_data;
create policy "Users can update own app data"
  on public.user_data for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(new.email, '用户'), '@', 1))
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = excluded.display_name,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email, raw_user_meta_data on auth.users
  for each row execute procedure public.handle_new_user();

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.login_events to authenticated;
grant select, insert, update on public.user_data to authenticated;
grant usage, select on all sequences in schema public to authenticated;
